# Generated by Django 5.0.1 on 2024-01-18 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='to_democrats',
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_to',
            field=models.CharField(choices=[('d', 'democrats'), ('r', 'respublicans')], default='d', max_length=1),
            preserve_default=False,
        ),
    ]
